name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["*"]

jobs:
  lint:
    name: Eslint + Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run lint
